### ISSUE TITLE
ImportError: cannot import name NavigationToolbar2Qt 

### ISSUE THREAD

**Issue by MuadDib69** [Gustry/GeoHealth#40]
ImportError: cannot import name NavigationToolbar2Qt 
Traceback (most recent call last):
  File "E:/QGis/apps/qgis/./python\qgis\utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "E:/QGis/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\__init__.py", line 23, in 
    from GeoHealth.src.plugin import GeoHealthPlugin
  File "E:/QGis/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\src\plugin.py", line 30, in 
    from GeoHealth.src.gui.main_window import MainDialog
  File "E:/QGis/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\src\gui\main_window.py", line 50, in 
    from GeoHealth.src.gui.analysis.stats_dialog import StatsWidget
  File "E:/QGis/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\src\gui\analysis\stats_dialog.py", line 35, in 
    from GeoHealth.src.core.graph_toolbar import CustomNavigationToolbar
  File "E:/QGis/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\src\core\graph_toolbar.py", line 27, in 
    from matplotlib.backends.backend_qt4agg import \
ImportError: cannot import name NavigationToolbar2Qt

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.13 Las Palmas, 8cba0bb9eb 

Python Path:
E:/QGis/apps/qgis/./python/plugins\processing
E:/QGis/apps/qgis/./python
C:/Users/MYUSER/.qgis2/python
C:/Users/MYUSER/.qgis2/python/plugins
E:/QGis/apps/qgis/./python/plugins
E:\QGis\bin\python27.zip
E:\QGis\apps\Python27\DLLs
E:\QGis\apps\Python27\lib
E:\QGis\apps\Python27\lib\plat-win
E:\QGis\apps\Python27\lib\lib-tk
E:\QGis\bin
E:\QGis\apps\Python27
E:\QGis\apps\Python27\lib\site-packages
E:\QGis\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
E:\QGis\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
E:\QGis\apps\Python27\lib\site-packages\win32
E:\QGis\apps\Python27\lib\site-packages\win32\lib
E:\QGis\apps\Python27\lib\site-packages\Pythonwin
E:\QGis\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
E:\QGis\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
E:\QGis\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
E:\QGis\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/MYUSER/.qgis2//python

**Comment by rumcajsz** [comment]
Same problem here.

ImportError: cannot import name NavigationToolbar2Qt 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\__init__.py", line 23, in 
    from GeoHealth.src.plugin import GeoHealthPlugin
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\src\plugin.py", line 30, in 
    from GeoHealth.src.gui.main_window import MainDialog
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\src\gui\main_window.py", line 50, in 
    from GeoHealth.src.gui.analysis.stats_dialog import StatsWidget
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\src\gui\analysis\stats_dialog.py", line 35, in 
    from GeoHealth.src.core.graph_toolbar import CustomNavigationToolbar
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MYUSER/.qgis2/python/plugins\GeoHealth\src\core\graph_toolbar.py", line 27, in 
    from matplotlib.backends.backend_qt4agg import \
ImportError: cannot import name NavigationToolbar2Qt


Python verzió: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS verzió 2.18.13 Las Palmas, 8cba0bb9eb 

Python elérési út:
C:\Users\MYUSER\.qgis2\python\plugins\GeoCoding\libs
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/MYUSER/.qgis2/python
C:/Users/MYUSER/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/MYUSER/.qgis2//python
C:\Users\MYUSER\.qgis2\python\plugins\mmqgis/forms
C:/Users/MYUSER/GIS

**Comment by Gustry** [comment]
Thanks for the ticket.

Is the Statist plugin working fine for you? (if you install it and use it)

**Comment by rumcajsz** [comment]
As I see, don't.
I installed, and open the window, but the statist window's table part is empty.
![kep](https://user-images.githubusercontent.com/6314509/32552528-8a29a500-c494-11e7-919e-3306e2b7b441.png)

**Comment by rumcajsz** [comment]
Maybe this API changes caused this error? https://matplotlib.org/api/api_changes.html#remove-navigationtoolbar2qtagg

**Comment by Gustry** [comment]
This API change is already covered here: 
https://github.com/Gustry/GeoHealth/blob/b9db02c68f9d8946dfe7938a61cfaf31af922a60/src/core/graph_toolbar.py#L23

**Comment by Gustry** [comment]
Can you do this in QGIS -> Plugins -> Python console:
```
import matplotlib
matplotlib.__version__
matplotlib.__file__
```

**Comment by rumcajsz** [comment]
So, I had install the newest QGIS (2.18.14) in a new machine (AMD64bit Windows 10), I tried to install this plugin, but same problem here too. 
The Python consol log:
```
import matplotlib
matplotlib.__version__
'2.0.0'
matplotlib.__file__
'C:\\PROGRA~1\\QGIS2~1.18\\apps\\Python27\\lib\\site-packages\\matplotlib\\__init__.py'
```
